### ISSUE TITLE
Range of PWM knob

### ISSUE THREAD

**Issue by jpa73** [gerb-ster/Curstis-VCO#1]
This control causes the VCO to cut out when either fully clockwise or fully anticlockwise.  The scope shows the pulse width changing as you'd expect over the rest of the range.  This may be by design, but in use it may benefit from reducing the range of the Pulse Width control to avoid the VCO from cutting out at either end of the range.

**Comment by jpa73** [comment]
Remove R51 and change out R49 to 91k.  This moderates the upper and lower ranges so that as the minimum or maximum settings the PW does not cause the VCO to cut out.

**Comment by jpa73** [comment]
This could be a documented option or a permanent change to the BOM.

**Comment by gerb-ster** [comment]
@jpa73 you are right, I've updated the schematics & documentation! version 1.2 is released :-) thanks for the debugging and suggestions!
